// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FilterProductsController from "./filter_products_controller.js"
application.register("filter-products", FilterProductsController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)
